# This is the production workflow. It will do a clean install of node dependencies, cache/restore them, build the source code, run tests,
# then build and push a docker image to dockerhub

name: Production CI/CD

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      REACT_APP_AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN }}
      REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.REACT_APP_AUTH0_CLIENT_ID }}
      REACT_APP_AUTH0_AUDIENCE: ${{ secrets.REACT_APP_AUTH0_AUDIENCE }}
      REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      SKIP_PREFLIGHT_CHECK: 'true'
    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install npm packages
      run: npm i

    - name: Create npm build
      run: npm run build

    - name: run integration and unit tests
      run: npm run ciTest
    
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: af912/react-landing-page
        tags: latest
        registry: docker.io
        # dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
